spring:
     application:
           name: customer-preference-service

     datasource:
           url: jdbc:mysql://localhost:3307/crm
           username: root
           password: admin

     jpa:
           show-sql: true	
           hibernate:
              ddl-auto: update

server:
     port: 8060